### ISSUE TITLE
kops changed release versions to include `v` prefix

### ISSUE THREAD

**Issue by joshbranham** [Antiarchitect/asdf-kops#4]
`kops` releases now use `v` in front of a version which breaks the download url here. They are now of the format:

`https://github.com/kubernetes/kops/releases/download/v1.15.1/kops-darwin-amd64` for instance.

Shall I open a PR and maybe try without the `v` for legacy support, and then with if not found?

**Comment by Antiarchitect** [comment]
Yep, If you can fix it properly - please do
